<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <IsPackable>True</IsPackable>
    <RootNamespace>Avalonia.Controls</RootNamespace>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <IsAotCompatible>true</IsAotCompatible>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <LangVersion>preview</LangVersion>
    <EnablePreviewFeatures>true</EnablePreviewFeatures>
    <Features>$(Features);runtime-async=off</Features>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <!--<AnalysisMode>AllEnabledByDefault</AnalysisMode>-->
    <AnalysisLevel>latest</AnalysisLevel>
    <EnableTrimAnalyzer>true</EnableTrimAnalyzer>
    <ILLinkTreatWarningsAsErrors>false</ILLinkTreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>TreeDataGrid.Avalonia</PackageId>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="..\..\readme.nuget.md" Pack="true" PackagePath="readme.md" Visible="false" />
    <None Include="..\..\docs\images\icon.png" Pack="true" PackagePath="icon.png" Visible="false" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.0" />
    <PackageReference Include="PolySharp" Version="1.15.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="11.0.100-preview.2.26159.112" />
    <PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.14.15">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <!--<PackageReference Include="IDisposableAnalyzers" Version="4.0.8" PrivateAssets="all" />-->
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="11.0.100-preview.2.26159.112" PrivateAssets="all" />
    <PackageReference Include="Roslynator.Analyzers" Version="4.15.0" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Avalonia.Controls.TreeDataGrid.Benchmark" />
    <InternalsVisibleTo Include="Avalonia.Controls.TreeDataGrid.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="StandardExtensions\**" />
    <None Remove="StandardExtensions\**" />
  </ItemGroup>

</Project>